/**
 * API: B2B 提案書自動生成
 *
 * POST /api/b2b/generate-proposal
 *
 * 目的: Gemini Proを使用して企業タイアップの提案書を自動生成
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  generateProposalWithGemini,
  formatProposalAsMarkdown,
} from '@/lib/b2b/proposal-generator';
import { generateInfluenceProof } from '@/lib/b2b/influence-proof-generator';
import {
  fetchPersonaById,
  createProposal,
} from '@/lib/supabase/b2b-partnership';
import type {
  GenerateProposalRequest,
  CompanyResearchData,
} from '@/types/b2b-partnership';

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as GenerateProposalRequest;

    const { persona_id, company_data, target_product, proposal_type, platforms } = body;

    // バリデーション
    if (!persona_id) {
      return NextResponse.json(
        {
          success: false,
          error: 'persona_id is required',
        },
        { status: 400 }
      );
    }

    if (!company_data) {
      return NextResponse.json(
        {
          success: false,
          error: 'company_data is required',
        },
        { status: 400 }
      );
    }

    console.log(`[B2B] Generating proposal for persona: ${persona_id}`);
    console.log(`[B2B] Target company: ${company_data.company_name}`);

    // ペルソナ情報を取得
    const persona = await fetchPersonaById(persona_id);

    // 影響力証明データを生成
    const influenceProof = await generateInfluenceProof(persona_id);

    console.log(`[B2B] Influence proof generated`);
    console.log(`  - Total followers: ${influenceProof.total_followers}`);
    console.log(`  - Monthly reach: ${influenceProof.monthly_reach}`);

    // Geminiで提案書を生成
    const proposalData = await generateProposalWithGemini(
      company_data,
      persona,
      influenceProof,
      target_product
    );

    console.log(`[B2B] Proposal generated by Gemini`);

    // データベースに保存
    const savedProposal = await createProposal({
      ...proposalData,
      persona_id,
      target_company: company_data.company_name,
      target_product,
      influence_proof: influenceProof,
      status: 'draft',
    });

    console.log(`[B2B] Proposal saved to database: ${savedProposal.id}`);

    // Markdown形式でフォーマット
    const markdown = formatProposalAsMarkdown(savedProposal, company_data, persona);

    return NextResponse.json(
      {
        success: true,
        proposal_id: savedProposal.id,
        proposal: savedProposal,
        markdown,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('[B2B] Error generating proposal:', error);

    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
