-- 全世界195カ国 配送ゾーンデータベース（続き）
-- ファイル: world_zones_complete_database.sql

-- 残りの国々（合計195カ国達成のため）
('AF', 'Afghanistan', 'アフガニスタン', '🇦🇫', 'Zone3', TRUE, '対応外', FALSE, '第2地帯', TRUE, 'Asia', FALSE),
('AL', 'Albania', 'アルバニア', '🇦🇱', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('DZ', 'Algeria', 'アルジェリア', '🇩🇿', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('AD', 'Andorra', 'アンドラ', '🇦🇩', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('AO', 'Angola', 'アンゴラ', '🇦🇴', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('AG', 'Antigua and Barbuda', 'アンティグア・バーブーダ', '🇦🇬', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('AM', 'Armenia', 'アルメニア', '🇦🇲', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('AZ', 'Azerbaijan', 'アゼルバイジャン', '🇦🇿', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('BS', 'Bahamas', 'バハマ', '🇧🇸', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('BB', 'Barbados', 'バルバドス', '🇧🇧', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('BY', 'Belarus', 'ベラルーシ', '🇧🇾', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('BZ', 'Belize', 'ベリーズ', '🇧🇿', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('BJ', 'Benin', 'ベナン', '🇧🇯', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('BT', 'Bhutan', 'ブータン', '🇧🇹', 'Zone3', TRUE, '対応外', FALSE, '第2地帯', TRUE, 'Asia', FALSE),
('BO', 'Bolivia', 'ボリビア', '🇧🇴', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'South America', FALSE),
('BA', 'Bosnia and Herzegovina', 'ボスニア・ヘルツェゴビナ', '🇧🇦', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('BW', 'Botswana', 'ボツワナ', '🇧🇼', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('BN', 'Brunei', 'ブルネイ', '🇧🇳', 'Zone2', TRUE, '対応外', FALSE, '第2地帯', TRUE, 'Asia', FALSE),
('BG', 'Bulgaria', 'ブルガリア', '🇧🇬', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('BF', 'Burkina Faso', 'ブルキナファソ', '🇧🇫', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('BI', 'Burundi', 'ブルンジ', '🇧🇮', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('CV', 'Cape Verde', 'カーボベルデ', '🇨🇻', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('CM', 'Cameroon', 'カメルーン', '🇨🇲', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('CF', 'Central African Republic', '中央アフリカ共和国', '🇨🇫', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('TD', 'Chad', 'チャド', '🇹🇩', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('KM', 'Comoros', 'コモロ', '🇰🇲', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('CG', 'Congo', 'コンゴ共和国', '🇨🇬', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('CD', 'Democratic Republic of Congo', 'コンゴ民主共和国', '🇨🇩', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('CR', 'Costa Rica', 'コスタリカ', '🇨🇷', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('HR', 'Croatia', 'クロアチア', '🇭🇷', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('CU', 'Cuba', 'キューバ', '🇨🇺', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('CY', 'Cyprus', 'キプロス', '🇨🇾', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('DJ', 'Djibouti', 'ジブチ', '🇩🇯', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('DM', 'Dominica', 'ドミニカ国', '🇩🇲', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('DO', 'Dominican Republic', 'ドミニカ共和国', '🇩🇴', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('EC', 'Ecuador', 'エクアドル', '🇪🇨', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'South America', FALSE),
('SV', 'El Salvador', 'エルサルバドル', '🇸🇻', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('GQ', 'Equatorial Guinea', '赤道ギニア', '🇬🇶', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('ER', 'Eritrea', 'エリトリア', '🇪🇷', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('EE', 'Estonia', 'エストニア', '🇪🇪', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('SZ', 'Eswatini', 'エスワティニ', '🇸🇿', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('ET', 'Ethiopia', 'エチオピア', '🇪🇹', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('FJ', 'Fiji', 'フィジー', '🇫🇯', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('GA', 'Gabon', 'ガボン', '🇬🇦', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('GM', 'Gambia', 'ガンビア', '🇬🇲', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('GE', 'Georgia', 'ジョージア', '🇬🇪', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('GD', 'Grenada', 'グレナダ', '🇬🇩', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('GT', 'Guatemala', 'グアテマラ', '🇬🇹', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('GN', 'Guinea', 'ギニア', '🇬🇳', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('GW', 'Guinea-Bissau', 'ギニアビサウ', '🇬🇼', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('GY', 'Guyana', 'ガイアナ', '🇬🇾', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'South America', FALSE),
('HT', 'Haiti', 'ハイチ', '🇭🇹', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('HN', 'Honduras', 'ホンジュラス', '🇭🇳', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('IS', 'Iceland', 'アイスランド', '🇮🇸', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('IQ', 'Iraq', 'イラク', '🇮🇶', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Middle East', FALSE),
('IR', 'Iran', 'イラン', '🇮🇷', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Middle East', FALSE),
('JM', 'Jamaica', 'ジャマイカ', '🇯🇲', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('KZ', 'Kazakhstan', 'カザフスタン', '🇰🇿', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('KG', 'Kyrgyzstan', 'キルギス', '🇰🇬', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('LV', 'Latvia', 'ラトビア', '🇱🇻', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('LS', 'Lesotho', 'レソト', '🇱🇸', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('LR', 'Liberia', 'リベリア', '🇱🇷', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('LY', 'Libya', 'リビア', '🇱🇾', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('LI', 'Liechtenstein', 'リヒテンシュタイン', '🇱🇮', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('LT', 'Lithuania', 'リトアニア', '🇱🇹', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('LU', 'Luxembourg', 'ルクセンブルク', '🇱🇺', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('MG', 'Madagascar', 'マダガスカル', '🇲🇬', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('MW', 'Malawi', 'マラウイ', '🇲🇼', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('MV', 'Maldives', 'モルディブ', '🇲🇻', 'Zone3', TRUE, '対応外', FALSE, '第2地帯', TRUE, 'Asia', FALSE),
('ML', 'Mali', 'マリ', '🇲🇱', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('MT', 'Malta', 'マルタ', '🇲🇹', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('MH', 'Marshall Islands', 'マーシャル諸島', '🇲🇭', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('MR', 'Mauritania', 'モーリタニア', '🇲🇷', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('MU', 'Mauritius', 'モーリシャス', '🇲🇺', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('FM', 'Micronesia', 'ミクロネシア', '🇫🇲', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('MD', 'Moldova', 'モルドバ', '🇲🇩', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('MC', 'Monaco', 'モナコ', '🇲🇨', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('MN', 'Mongolia', 'モンゴル', '🇲🇳', 'Zone3', TRUE, '対応外', FALSE, '第2地帯', TRUE, 'Asia', FALSE),
('ME', 'Montenegro', 'モンテネグロ', '🇲🇪', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('MZ', 'Mozambique', 'モザンビーク', '🇲🇿', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('NA', 'Namibia', 'ナミビア', '🇳🇦', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('NR', 'Nauru', 'ナウル', '🇳🇷', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('NP', 'Nepal', 'ネパール', '🇳🇵', 'Zone3', TRUE, '対応外', FALSE, '第2地帯', TRUE, 'Asia', FALSE),
('NI', 'Nicaragua', 'ニカラグア', '🇳🇮', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('NE', 'Niger', 'ニジェール', '🇳🇪', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('MK', 'North Macedonia', '北マケドニア', '🇲🇰', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('PW', 'Palau', 'パラオ', '🇵🇼', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('PA', 'Panama', 'パナマ', '🇵🇦', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('PG', 'Papua New Guinea', 'パプアニューギニア', '🇵🇬', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('PY', 'Paraguay', 'パラグアイ', '🇵🇾', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'South America', FALSE),
('RO', 'Romania', 'ルーマニア', '🇷🇴', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('RW', 'Rwanda', 'ルワンダ', '🇷🇼', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('KN', 'Saint Kitts and Nevis', 'セントクリストファー・ネーヴィス', '🇰🇳', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('LC', 'Saint Lucia', 'セントルシア', '🇱🇨', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('VC', 'Saint Vincent and the Grenadines', 'セントビンセント・グレナディーン', '🇻🇨', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('WS', 'Samoa', 'サモア', '🇼🇸', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('SM', 'San Marino', 'サンマリノ', '🇸🇲', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('ST', 'Sao Tome and Principe', 'サントメ・プリンシペ', '🇸🇹', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('RS', 'Serbia', 'セルビア', '🇷🇸', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('SC', 'Seychelles', 'セーシェル', '🇸🇨', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('SL', 'Sierra Leone', 'シエラレオネ', '🇸🇱', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('SK', 'Slovakia', 'スロバキア', '🇸🇰', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('SI', 'Slovenia', 'スロベニア', '🇸🇮', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('SB', 'Solomon Islands', 'ソロモン諸島', '🇸🇧', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('SO', 'Somalia', 'ソマリア', '🇸🇴', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('SS', 'South Sudan', '南スーダン', '🇸🇸', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('SD', 'Sudan', 'スーダン', '🇸🇩', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('SR', 'Suriname', 'スリナム', '🇸🇷', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'South America', FALSE),
('SY', 'Syria', 'シリア', '🇸🇾', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Middle East', FALSE),
('TJ', 'Tajikistan', 'タジキスタン', '🇹🇯', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('TZ', 'Tanzania', 'タンザニア', '🇹🇿', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('TL', 'Timor-Leste', '東ティモール', '🇹🇱', 'Zone3', TRUE, '対応外', FALSE, '第2地帯', TRUE, 'Asia', FALSE),
('TG', 'Togo', 'トーゴ', '🇹🇬', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('TO', 'Tonga', 'トンガ', '🇹🇴', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('TT', 'Trinidad and Tobago', 'トリニダード・トバゴ', '🇹🇹', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'North America', FALSE),
('TM', 'Turkmenistan', 'トルクメニスタン', '🇹🇲', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('TV', 'Tuvalu', 'ツバル', '🇹🇻', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('UG', 'Uganda', 'ウガンダ', '🇺🇬', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('UA', 'Ukraine', 'ウクライナ', '🇺🇦', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('UY', 'Uruguay', 'ウルグアイ', '🇺🇾', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'South America', FALSE),
('UZ', 'Uzbekistan', 'ウズベキスタン', '🇺🇿', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Asia', FALSE),
('VU', 'Vanuatu', 'バヌアツ', '🇻🇺', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Oceania', FALSE),
('VA', 'Vatican City', 'バチカン市国', '🇻🇦', 'Zone2', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Europe', FALSE),
('VE', 'Venezuela', 'ベネズエラ', '🇻🇪', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'South America', FALSE),
('YE', 'Yemen', 'イエメン', '🇾🇪', 'Zone3', TRUE, '対応外', FALSE, '第3地帯', TRUE, 'Middle East', FALSE),
('ZM', 'Zambia', 'ザンビア', '🇿🇲', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE),
('ZW', 'Zimbabwe', 'ジンバブエ', '🇿🇼', 'Zone3', TRUE, '対応外', FALSE, '第5地帯', TRUE, 'Africa', FALSE);

-- 統計情報表示
SELECT '=== 全世界195カ国データベース構築完了 ===' as result;

SELECT 
    '配送会社別対応国統計' as metric,
    'eLogi: ' || COUNT(*) FILTER (WHERE elogi_supported = TRUE) || 'カ国' as elogi_count,
    'CPass: ' || COUNT(*) FILTER (WHERE cpass_supported = TRUE) || 'カ国' as cpass_count,
    '日本郵便: ' || COUNT(*) FILTER (WHERE jppost_supported = TRUE) || 'カ国' as jppost_count,
    '総登録国数: ' || COUNT(*) || 'カ国' as total_countries
FROM country_zones_extended;

SELECT 
    'ゾーン別国数統計' as metric,
    elogi_zone,
    COUNT(*) as country_count
FROM country_zones_extended 
WHERE elogi_supported = TRUE 
GROUP BY elogi_zone 
ORDER BY elogi_zone;

SELECT '✅ 全世界195カ国配送ゾーンデータベース完全構築完了' as final_result;